global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['shrtener:8000']
  - job_name: shrtener
    metrics_path: /metrics
    static_configs:
      - targets:
          - shrtener:8000