server:
  host: localhost
  port: 5000
  protocol: http

database:
  host: 'localhost:26257'
  db_name: shrtener
  username: admin
  password: admin
  auth_enabled: false
  skip_schema: true

auth:
  enabled: true
