server:
  host: localhost
  port: 5000
  protocol: http

database:
  host: 'localhost:26257'
  db_name: shrtner
  username: root
  password: admin
  auth_enabled: false
  skip_schema: false

auth:
  enabled: false

dns: 'http://localhost:5000'

logging:
  level: info # levels: info, warning, error, debug
  format: json
  output: stdout # output: stdout, file
  directory: logs
